package com.example.backend.api.dto;

import java.util.List;

import io.swagger.v3.oas.annotations.media.Schema;

public class QueryResponse {

  @Schema(description = "Final answer generated by the model", example = "This document describes the project architecture and how to run the system locally.")
  public String answer;

  @Schema(description = "Citations used to ground the answer")
  public List<CitationDto> citations;

  @Schema(description = "Number of retrieved chunks used in generation", example = "3")
  public int retrievedCount;

  public QueryResponse() {
  }

  public QueryResponse(String answer, List<CitationDto> citations, int retrievedCount) {
    this.answer = answer;
    this.citations = citations;
    this.retrievedCount = retrievedCount;
  }
}